#!/bin/bash

if pgrep -x main > /dev/null
then
        is_running=true
else
        is_running=false
fi

status()
{
	if [ $is_running = true ]; then
		echo "Application is running."
	else
		echo "Application is not running."
	fi
}

start() 
{
        if [ $is_running = true ]; then
                echo "Application is started."
                exit 1
        else
                main &
        fi
}

stop()
{
        if [ $is_running = true ]; then
                pkill main
        else
                echo "Application is not running."
                exit 1
        fi
}

build()
{
	go install main.go
}

update() 
{
	git pull
}


case "$1" in
	"status")	status		;;
	"start")	start		;;
	"stop")		stop		;;
	"build")	build		;;
	"update")	update		;;
	*)		echo "To run script: ./site start|stop|status|build|update"
			exit 1		;;
esac


