#!/bin/bash

if pgrep -x main > /dev/null
then
        is_running=true
else
        is_running=false
fi

if [ $1 == "status" ]; then
        if [ $is_running = true ]; then
                echo "App is running"
        else
                echo "App is not running"
        fi
fi

if [ $1 == "start" ]; then
        if [ $is_running = true ]; then
                echo "Application is all ready running."
                exit 1
        else
                main &
        fi
fi

if [ $1 == "stop" ]; then
        if [ $is_running = true ]; then
                pkill main
        else
                echo "Application is not running."
                exit 1
        fi
fi